plugins {
    id 'com.android.application'
}

android {
    namespace 'com.leosprojects.busdisplay'
    compileSdk 35

    defaultConfig {
        applicationId 'com.leosprojects.busdisplay'
        minSdk 31
        targetSdk 35
        versionCode 4
        versionName '0.4.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    androidResources {
        noCompress += ['ogg', 'wav']
    }
}
